### ISSUE TITLE
crash with abyssallcraft

### ISSUE THREAD

**Issue by TandJ21** [BarelyAlive/Nether-Tweaks#4]
[crash-2017-07-06_22.35.15-client.txt](https://github.com/BarelyAlive/Nether-Tweaks/files/1129378/crash-2017-07-06_22.35.15-client.txt)

**Comment by TandJ21** [comment]
it crashes with abyssallcraft and we would like maybe a fix as it would be great in our pack dimensional hell the search for peace as you start in the nether we would like your mod for its nether enhancements >

**Comment by TandJ21** [comment]
i cannot remove abyssalcraft as it is important to the pack

**Comment by TandJ21** [comment]
Also lovely that your "core" mod is closed source
But anyways, the metadata they apply when registering their saltpeter/nitre ore to the OreDict doesn't match the actual metadata that block uses
So your screwing up somewhere

**Comment by Gaprosys** [comment]
Hi,

Occurs the crash still?
If yes, when occurs the crash?

Would be nice to see reply soon.
Have a nice day.

- Gaprosys
