### ISSUE TITLE
Removed Recipes in JEI

### ISSUE THREAD

**Issue by digerbop** [BarelyAlive/Nether-Tweaks#42]
I have a modpack with NetherEx, BetterNether, PrimalCore, and Nether-Tweaks. As soon as I add Nether Tweaks to the pack, a bunch of recipes in JEI disappear. Some examples are oakwood planks and stone pickaxe. I can still craft these items in a crafting table, but I can't see the recipes.

**Comment by BarelyAlive** [comment]
Thanks. We'll look into it and see how it can be resolved.

**Comment by BarelyAlive** [comment]
It would help us a lot to solve the problem if you could tell us the versions of the mods you use and the one from Forge.

**Comment by digerbop** [comment]
I have found out the problem. PrimalCore is the mod that is causing the recipe issues. Once I remove primal core or Nether Teaks from the pack, everything works. I am using PrimalCore-1.12.2-0.6.105 and forge 14.23.5.2847

**Comment by BarelyAlive** [comment]
As far as I could see, PrimalCore also causes the error with SHFCore (the library for NTM) alone. But since SFHCore does nothing with JEI or recipes, the error is probably caused by PrimalCore alone. Therefore I think this can be closed here.
